---For Users Table
insert into users (first_name, last_name, is_deleted, date_created) values ('Candida', 'Batistelli', true, '2022-05-13');
insert into users (first_name, last_name, is_deleted, date_created) values ('Dyan', 'Avarne', false, '2022-08-11');
insert into users (first_name, last_name, is_deleted, date_created) values ('Valencia', 'Hatfield', false, '2022-04-06');
insert into users (first_name, last_name, is_deleted, date_created) values ('Jenelle', 'Tollow', false, '2022-04-16');
insert into users (first_name, last_name, is_deleted, date_created) values ('Fifine', 'Notton', false, '2022-04-28');
insert into users (first_name, last_name, is_deleted, date_created) values ('Hermie', 'Hazleton', true, '2022-05-27');
insert into users (first_name, last_name, is_deleted, date_created) values ('Selinda', 'Kall', true, '2022-12-12');
insert into users (first_name, last_name, is_deleted, date_created) values ('Alley', 'Archley', false, '2022-04-30');
insert into users (first_name, last_name, is_deleted, date_created) values ('Newton', 'Thyer', true, '2022-07-07');
insert into users (first_name, last_name, is_deleted, date_created) values ('Yulma', 'Swalough', false, '2023-02-08');
insert into users (first_name, last_name, is_deleted, date_created) values ('Adelina', 'Whittam', false, '2022-06-28');
insert into users (first_name, last_name, is_deleted, date_created) values ('Raychel', 'Skiplorne', true, '2023-02-21');
insert into users (first_name, last_name, is_deleted, date_created) values ('Haley', 'Fisk', true, '2022-06-28');
insert into users (first_name, last_name, is_deleted, date_created) values ('Joyous', 'Denecamp', false, '2022-08-20');
insert into users (first_name, last_name, is_deleted, date_created) values ('Malanie', 'Blethin', true, '2022-03-20');
insert into users (first_name, last_name, is_deleted, date_created) values ('Nehemiah', 'Ossipenko', false, '2023-01-02');
insert into users (first_name, last_name, is_deleted, date_created) values ('Leonidas', 'Tripett', false, '2022-03-20');
insert into users (first_name, last_name, is_deleted, date_created) values ('Damiano', 'Braizier', false, '2023-01-05');
insert into users (first_name, last_name, is_deleted, date_created) values ('Irene', 'Hitcham', true, '2022-11-22');
insert into users (first_name, last_name, is_deleted, date_created) values ('Antonetta', 'Rowston', false, '2022-10-03');
insert into users (first_name, last_name, is_deleted, date_created) values ('Whitby', 'McKirton', false, '2022-09-17');
insert into users (first_name, last_name, is_deleted, date_created) values ('Tressa', 'Renzullo', false, '2022-12-14');
insert into users (first_name, last_name, is_deleted, date_created) values ('Clarita', 'Lewcock', false, '2022-06-30');
insert into users (first_name, last_name, is_deleted, date_created) values ('Caritta', 'Derx', false, '2023-02-08');
insert into users (first_name, last_name, is_deleted, date_created) values ('Manolo', 'McGrouther', false, '2023-02-03');
---For Contact
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Misty', 'Yakebovitch', false, '2023-01-05', 1);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Jerrie', 'McQuin', false, '2023-02-01', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Mariele', 'Thoma', true, '2022-06-14', 10);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Radcliffe', 'Gaskin', false, '2022-04-27', 4);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Elmo', 'Tue', true, '2022-03-27', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Octavia', 'Favelle', false, '2023-01-09', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Johnna', 'Cloney', false, '2022-11-12', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Winny', 'Verey', false, '2022-03-15', 12);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Mandy', 'Loram', false, '2023-02-24', 1);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Starlin', 'Rannald', false, '2023-03-11', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Tally', 'Dumbar', true, '2022-07-05', 5);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Georgette', 'Rosettini', false, '2022-12-27', 22);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Shanta', 'Botwright', true, '2022-08-25', 20);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Daren', 'Vickerstaff', false, '2022-07-23', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Coralyn', 'Attwoul', true, '2022-04-19', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Roselia', 'Clover', true, '2022-04-29', 12);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Thaxter', 'McBrearty', false, '2022-03-19', 22);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Matthus', 'Katzmann', true, '2022-08-06', 3);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Barrie', 'de Nore', true, '2022-07-01', 21);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Laetitia', 'Veevers', false, '2022-06-07', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Dacey', 'Cassin', false, '2022-06-24', 15);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Oralee', 'O''Kieran', true, '2023-01-16', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Christoffer', 'Towell', false, '2022-09-30', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Zackariah', 'Avramovic', true, '2022-05-17', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Latrina', 'Anfonsi', false, '2022-04-14', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Pail', 'Catlow', false, '2022-03-28', 9);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Fifine', 'Helgass', false, '2022-08-13', 2);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Dorree', 'Colhoun', false, '2022-06-04', 11);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Vannie', 'Conford', false, '2022-09-05', 14);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Sibylle', 'Ibeson', false, '2022-06-09', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Gray', 'Pont', false, '2022-12-03', 25);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Garald', 'Ferrai', false, '2022-04-16', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Crissie', 'Sinclaire', false, '2022-12-22', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Loree', 'Albutt', false, '2023-01-14', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Ella', 'Curryer', false, '2022-05-22', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Ahmed', 'Choffin', false, '2022-05-06', 9);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Bryant', 'Bedward', false, '2022-06-03', 19);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Marj', 'McAreavey', false, '2022-10-27', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Cordi', 'Nigh', false, '2022-09-20', 21);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Feodora', 'Lionel', true, '2022-10-29', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Sydney', 'Pevie', true, '2022-08-11', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Corney', 'Bereford', false, '2022-10-24', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Donnajean', 'Shoard', false, '2022-03-29', 20);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Cart', 'Dessant', false, '2022-04-28', 25);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Berky', 'Crayden', false, '2023-02-05', 8);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Flinn', 'Harkess', false, '2022-10-25', 11);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Hart', 'Lightning', false, '2022-06-19', 10);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Vito', 'Alcalde', false, '2022-07-21', 8);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Nadiya', 'Roskelly', true, '2022-06-19', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Rodolfo', 'McCreery', false, '2022-05-09', 4);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Guss', 'Geratasch', false, '2022-07-12', 2);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Prince', 'McCrorie', false, '2022-04-22', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Madeline', 'Pash', false, '2022-04-02', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Leoline', 'Upton', false, '2022-12-29', 23);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Haven', 'Childs', true, '2022-12-23', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Gareth', 'Fogel', true, '2022-12-08', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Collen', 'Boland', true, '2022-03-17', 10);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Angil', 'Lukock', true, '2022-07-10', 11);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Tresa', 'Jatczak', false, '2022-11-09', 15);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Casie', 'Startin', true, '2022-06-21', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Brena', 'Ripley', false, '2022-06-15', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Mable', 'Lount', true, '2022-10-01', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Erda', 'Fahrenbacher', true, '2022-08-24', 12);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Sada', 'Pfleger', true, '2022-12-06', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Annmarie', 'Duggan', false, '2022-06-06', 21);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Padraic', 'Kerby', true, '2022-04-09', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Xerxes', 'Sproston', false, '2022-12-18', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Clim', 'Boyda', true, '2022-07-04', 3);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Ulick', 'Stirman', false, '2023-02-24', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Fayth', 'Broadstock', true, '2022-09-05', 2);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Barthel', 'Ingon', false, '2022-10-11', 12);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Roxanna', 'Filon', false, '2022-11-20', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Caprice', 'Pear', false, '2022-05-25', 4);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Gonzalo', 'Seeks', false, '2022-09-15', 24);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Arleta', 'Catton', false, '2022-05-01', 3);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Brnaby', 'Macguire', false, '2022-09-26', 14);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Erich', 'Glaysher', true, '2022-04-16', 1);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Harrietta', 'Damiral', false, '2022-06-22', 9);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Donaugh', 'Kenealy', false, '2022-12-22', 8);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Bobinette', 'Sheasby', false, '2022-12-27', 18);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Karolina', 'Tampin', false, '2022-12-03', 17);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Carter', 'Stolz', true, '2022-08-13', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Aldon', 'Rechert', true, '2022-11-07', 12);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Marchall', 'Rilings', true, '2022-05-16', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Cletis', 'Huxstep', false, '2022-07-20', 3);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Avictor', 'Bendon', false, '2022-06-13', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Gipsy', 'Margaret', false, '2022-06-26', 23);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Kate', 'Vila', false, '2022-08-21', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Dominique', 'Robelin', true, '2022-05-23', 9);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Brenna', 'Pearle', true, '2022-12-21', 6);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Ramon', 'Shotton', false, '2022-06-25', 4);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Lindon', 'Levicount', false, '2022-10-31', 3);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Sibilla', 'Styles', false, '2022-09-21', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Hedi', 'Rice', false, '2022-12-03', 16);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Pedro', 'Durbin', false, '2022-12-01', 14);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Debor', 'Blizard', false, '2022-03-21', 14);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Bethanne', 'Rockell', true, '2022-04-30', 7);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Fernanda', 'Standrin', false, '2022-08-29', 13);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Ilka', 'Bore', false, '2022-10-29', 8);
insert into contact (first_name, last_name, is_deleted, date_created, user_id) values ('Zonnya', 'Derobert', false, '2023-01-01', 25);
---For email table
insert into email (email, is_deleted, contact_id) values ('blindberg0@bing.com', false, 34);
insert into email (email, is_deleted, contact_id) values ('kexcell1@unc.edu', true, 33);
insert into email (email, is_deleted, contact_id) values ('jfallowes2@google.ru', false, 25);
insert into email (email, is_deleted, contact_id) values ('lmacgibbon3@dyndns.org', false, 70);
insert into email (email, is_deleted, contact_id) values ('tdufaur4@fotki.com', true, 19);
insert into email (email, is_deleted, contact_id) values ('fjakovijevic5@com.com', false, 67);
insert into email (email, is_deleted, contact_id) values ('crackley6@nifty.com', true, 1);
insert into email (email, is_deleted, contact_id) values ('ppartener7@mapquest.com', true, 5);
insert into email (email, is_deleted, contact_id) values ('mplumridege8@businessinsider.com', true, 19);
insert into email (email, is_deleted, contact_id) values ('ljessett9@blog.com', false, 91);
insert into email (email, is_deleted, contact_id) values ('wmatteolia@vkontakte.ru', false, 66);
insert into email (email, is_deleted, contact_id) values ('cradkib@google.pl', false, 7);
insert into email (email, is_deleted, contact_id) values ('ddobinsonc@i2i.jp', false, 63);
insert into email (email, is_deleted, contact_id) values ('emckertond@booking.com', false, 25);
insert into email (email, is_deleted, contact_id) values ('smccraye@twitpic.com', true, 37);
insert into email (email, is_deleted, contact_id) values ('tjasiakf@berkeley.edu', true, 33);
insert into email (email, is_deleted, contact_id) values ('cfarrellg@pinterest.com', true, 100);
insert into email (email, is_deleted, contact_id) values ('dgodwynh@google.com.au', true, 14);
insert into email (email, is_deleted, contact_id) values ('wmckimi@imageshack.us', false, 32);
insert into email (email, is_deleted, contact_id) values ('nbootherj@senate.gov', false, 52);
insert into email (email, is_deleted, contact_id) values ('vcurrk@amazon.co.uk', true, 37);
insert into email (email, is_deleted, contact_id) values ('cfishbournl@msn.com', true, 27);
insert into email (email, is_deleted, contact_id) values ('fgrinyakinm@howstuffworks.com', false, 6);
insert into email (email, is_deleted, contact_id) values ('raslamn@technorati.com', true, 8);
insert into email (email, is_deleted, contact_id) values ('ksimiolio@wufoo.com', true, 68);
insert into email (email, is_deleted, contact_id) values ('ebrendep@youku.com', true, 80);
insert into email (email, is_deleted, contact_id) values ('mriehmq@prnewswire.com', true, 82);
insert into email (email, is_deleted, contact_id) values ('rgillicer@theguardian.com', true, 62);
insert into email (email, is_deleted, contact_id) values ('ldeanes@netscape.com', false, 5);
insert into email (email, is_deleted, contact_id) values ('lhollowt@admin.ch', false, 80);
insert into email (email, is_deleted, contact_id) values ('gmaddamsu@google.com.hk', false, 52);
insert into email (email, is_deleted, contact_id) values ('cmckernanv@yellowbook.com', true, 35);
insert into email (email, is_deleted, contact_id) values ('amundellw@cocolog-nifty.com', false, 32);
insert into email (email, is_deleted, contact_id) values ('origmondx@usa.gov', false, 26);
insert into email (email, is_deleted, contact_id) values ('kjazey@gnu.org', true, 88);
insert into email (email, is_deleted, contact_id) values ('cgilfoyz@so-net.ne.jp', false, 100);
insert into email (email, is_deleted, contact_id) values ('banetts10@telegraph.co.uk', true, 37);
insert into email (email, is_deleted, contact_id) values ('mewbanche11@123-reg.co.uk', true, 2);
insert into email (email, is_deleted, contact_id) values ('zleades12@homestead.com', false, 61);
insert into email (email, is_deleted, contact_id) values ('yjakobsson13@networksolutions.com', false, 36);
insert into email (email, is_deleted, contact_id) values ('sturmel14@ehow.com', true, 53);
insert into email (email, is_deleted, contact_id) values ('lpharro15@barnesandnoble.com', true, 32);
insert into email (email, is_deleted, contact_id) values ('mblizard16@1und1.de', false, 23);
insert into email (email, is_deleted, contact_id) values ('draiman17@e-recht24.de', false, 12);
insert into email (email, is_deleted, contact_id) values ('lsaladine18@nps.gov', true, 64);
insert into email (email, is_deleted, contact_id) values ('mpalley19@seattletimes.com', false, 73);
insert into email (email, is_deleted, contact_id) values ('ogodball1a@ftc.gov', false, 48);
insert into email (email, is_deleted, contact_id) values ('mmacieiczyk1b@ox.ac.uk', true, 95);
insert into email (email, is_deleted, contact_id) values ('abras1c@tuttocitta.it', true, 30);
insert into email (email, is_deleted, contact_id) values ('gschorah1d@reddit.com', true, 15);
insert into email (email, is_deleted, contact_id) values ('mvasyukhichev1e@go.com', false, 48);
insert into email (email, is_deleted, contact_id) values ('jfarrears1f@constantcontact.com', false, 60);
insert into email (email, is_deleted, contact_id) values ('cmccroft1g@de.vu', true, 38);
insert into email (email, is_deleted, contact_id) values ('mluppitt1h@cafepress.com', false, 9);
insert into email (email, is_deleted, contact_id) values ('tlukins1i@squarespace.com', true, 29);
insert into email (email, is_deleted, contact_id) values ('tsplaven1j@nba.com', true, 74);
insert into email (email, is_deleted, contact_id) values ('kjacob1k@mediafire.com', false, 53);
insert into email (email, is_deleted, contact_id) values ('sdummigan1l@answers.com', true, 100);
insert into email (email, is_deleted, contact_id) values ('rhirjak1m@google.it', true, 51);
insert into email (email, is_deleted, contact_id) values ('rkrauss1n@whitehouse.gov', true, 65);
insert into email (email, is_deleted, contact_id) values ('vmobley1o@telegraph.co.uk', false, 21);
insert into email (email, is_deleted, contact_id) values ('dmayow1p@harvard.edu', true, 37);
insert into email (email, is_deleted, contact_id) values ('kpetrelli1q@webs.com', true, 15);
insert into email (email, is_deleted, contact_id) values ('kkaines1r@soundcloud.com', true, 35);
insert into email (email, is_deleted, contact_id) values ('cairs1s@theguardian.com', false, 100);
insert into email (email, is_deleted, contact_id) values ('jcaulfield1t@examiner.com', false, 66);
insert into email (email, is_deleted, contact_id) values ('tyeldon1u@cpanel.net', true, 35);
insert into email (email, is_deleted, contact_id) values ('tgilbart1v@zdnet.com', false, 41);
insert into email (email, is_deleted, contact_id) values ('ctenby1w@twitpic.com', false, 16);
insert into email (email, is_deleted, contact_id) values ('gtarbath1x@yellowbook.com', false, 56);
insert into email (email, is_deleted, contact_id) values ('ccomport1y@ycombinator.com', true, 35);
insert into email (email, is_deleted, contact_id) values ('eduncanson1z@umich.edu', true, 99);
insert into email (email, is_deleted, contact_id) values ('fastill20@odnoklassniki.ru', false, 82);
insert into email (email, is_deleted, contact_id) values ('agibbens21@miibeian.gov.cn', false, 92);
insert into email (email, is_deleted, contact_id) values ('btranfield22@1und1.de', false, 81);
insert into email (email, is_deleted, contact_id) values ('bredd23@surveymonkey.com', true, 34);
insert into email (email, is_deleted, contact_id) values ('abodycote24@illinois.edu', true, 97);
insert into email (email, is_deleted, contact_id) values ('psharvill25@google.co.uk', true, 57);
insert into email (email, is_deleted, contact_id) values ('dcupitt26@nps.gov', true, 69);
insert into email (email, is_deleted, contact_id) values ('galonso27@tmall.com', true, 26);
insert into email (email, is_deleted, contact_id) values ('cbergeon28@cisco.com', false, 2);
insert into email (email, is_deleted, contact_id) values ('tbratch29@cyberchimps.com', true, 4);
insert into email (email, is_deleted, contact_id) values ('ogellibrand2a@mozilla.org', false, 66);
insert into email (email, is_deleted, contact_id) values ('tredhole2b@ucsd.edu', false, 91);
insert into email (email, is_deleted, contact_id) values ('scottle2c@ning.com', false, 76);
insert into email (email, is_deleted, contact_id) values ('agrogono2d@ask.com', true, 84);
insert into email (email, is_deleted, contact_id) values ('aleaming2e@vk.com', false, 17);
insert into email (email, is_deleted, contact_id) values ('msaph2f@yellowpages.com', false, 53);
insert into email (email, is_deleted, contact_id) values ('bbickerton2g@gov.uk', true, 88);
insert into email (email, is_deleted, contact_id) values ('ibuttriss2h@sun.com', false, 24);
insert into email (email, is_deleted, contact_id) values ('jchichgar2i@hao123.com', true, 10);
insert into email (email, is_deleted, contact_id) values ('ftoten2j@tinypic.com', true, 34);
insert into email (email, is_deleted, contact_id) values ('dscrine2k@tiny.cc', true, 75);
insert into email (email, is_deleted, contact_id) values ('ewendover2l@buzzfeed.com', true, 33);
insert into email (email, is_deleted, contact_id) values ('vewbanke2m@hibu.com', false, 70);
insert into email (email, is_deleted, contact_id) values ('cpurple2n@deliciousdays.com', true, 15);
insert into email (email, is_deleted, contact_id) values ('vcheshire2o@ocn.ne.jp', true, 19);
insert into email (email, is_deleted, contact_id) values ('sheadford2p@marriott.com', false, 26);
insert into email (email, is_deleted, contact_id) values ('yveldens2q@tripadvisor.com', true, 44);
insert into email (email, is_deleted, contact_id) values ('wjanicijevic2r@wix.com', false, 8);
--for phone_number
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+452793651308', 73, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348357573266', 37, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+349308325183', 65, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+344787690317', 9, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346891542332', 67, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+349371106670', 51, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+342833957700', 19, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348171693158', 51, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341171664099', 21, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348263899423', 35, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341415387035', 70, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+342224205017', 10, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+342728292666', 22, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346522659272', 8, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+347972173906', 30, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+342186922043', 3, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346948320748', 12, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348335016563', 32, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+347873266423', 78, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348149307935', 50, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+343255383245', 65, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+344997399325', 28, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346464944315', 72, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346105270567', 33, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+342526011406', 4, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341841054359', 34, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348003659860', 82, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348214445142', 16, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+343351890228', 79, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+347483145987', 41, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341164643820', 77, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+346634309918', 33, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+347634293328', 34, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+349101186464', 51, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+349608781763', 67, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+345301729992', 58, true);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341802453461', 13, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+341061316053', 62, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+345941078046', 31, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+345892847249', 54, false);
insert into numbers_of_phone (phone_number, contact_id, is_deleted) values ('+348272362747', 80, false);